# Generated by Django 3.2.16 on 2023-01-21 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_newuser_degree'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='degree',
            field=models.CharField(blank=True, choices=[('1', 'B.TECH'), ('2', 'M.TECH'), ('3', 'MSC')], max_length=6, null=True),
        ),
    ]
