# Generated by Django 3.2.16 on 2023-01-23 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_newuser_degree'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='degree',
            field=models.CharField(blank=True, choices=[('B.TECH', 'B.TECH'), ('M.TECH', 'M.TECH'), ('MSC', 'MSC')], max_length=6, null=True),
        ),
    ]
