# Generated by Django 3.2.16 on 2023-01-18 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20230118_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
