# Generated by Django 3.2.16 on 2023-01-24 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_newuser_degree'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='degree',
            field=models.CharField(choices=[('B.TECH', 'B.TECH'), ('M.TECH', 'M.TECH'), ('MSC', 'MSC')], max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='program',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='year',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
