# Generated by Django 3.2.16 on 2023-01-23 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_blogpost_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='month_year',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
