# Generated by Django 3.2.16 on 2023-01-23 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20230123_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='job_offer',
            field=models.CharField(blank=True, choices=[('Summer Internship', 'Summer Internship'), ('Winter Internship & Job', 'Winter Internship & Job'), ('Job', 'Job'), ('Winter Internship Only', 'Winter Internship Only')], max_length=25, null=True),
        ),
    ]
